// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHO5oPUGGFpS0Fz31tfGMa6nIrT7A64x0',
    appId: '1:535969102972:web:59384b8e5e9bacc01a5df9',
    messagingSenderId: '535969102972',
    projectId: 'projectsos-e391f',
    authDomain: 'projectsos-e391f.firebaseapp.com',
    storageBucket: 'projectsos-e391f.firebasestorage.app',
    measurementId: 'G-T3WQEP83VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7dKhKlJakXpYW-XWAd6ZXZyNQBATtS0Y',
    appId: '1:535969102972:android:ba73e874c0b9aeee1a5df9',
    messagingSenderId: '535969102972',
    projectId: 'projectsos-e391f',
    storageBucket: 'projectsos-e391f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNEqpgfMoYc-YFxRzVWZLiXpKCnxd4Uc',
    appId: '1:535969102972:ios:c018853d28cf1bca1a5df9',
    messagingSenderId: '535969102972',
    projectId: 'projectsos-e391f',
    storageBucket: 'projectsos-e391f.firebasestorage.app',
    iosClientId: '535969102972-2d8cp7hsq3l2415s395udk5t299uqbih.apps.googleusercontent.com',
    iosBundleId: 'com.raksha.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrNEqpgfMoYc-YFxRzVWZLiXpKCnxd4Uc',
    appId: '1:535969102972:ios:c018853d28cf1bca1a5df9',
    messagingSenderId: '535969102972',
    projectId: 'projectsos-e391f',
    storageBucket: 'projectsos-e391f.firebasestorage.app',
    iosClientId: '535969102972-2d8cp7hsq3l2415s395udk5t299uqbih.apps.googleusercontent.com',
    iosBundleId: 'com.raksha.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHO5oPUGGFpS0Fz31tfGMa6nIrT7A64x0',
    appId: '1:535969102972:web:64cd65f051d511d01a5df9',
    messagingSenderId: '535969102972',
    projectId: 'projectsos-e391f',
    authDomain: 'projectsos-e391f.firebaseapp.com',
    storageBucket: 'projectsos-e391f.firebasestorage.app',
    measurementId: 'G-YM537EVDMJ',
  );
}
